services:
  fibonacci-api:
    image: fibonacci-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "0:8080" # load balancer will forward to this
    deploy:
      replicas: 3