services:
  fibonacci-api:
    image: fibonacci-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80" # load balancer will forward to this
    deploy:
      replicas: 3